server:
  port: 8080
  servlet:
    context-path: "/api"
api:
  name: 'User Api'
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:file:./users
    driverClassName: org.h2.Driver
    username: sa
    password: password
